### ISSUE TITLE
Logging interval for Tensorboard

### ISSUE THREAD

**Issue by dandelin** [coax-dev/coax#1]
First of all, thanks a lot for the library. I'm really enjoying coax and its modular design.

Currently `coax.wrappers.TrainMonitor` call `self.tensorboard.add_scalar` for every episode.
As a result, learning a few million episodes would blow the logging file, and the browser immediately freezes when rendering the chart.
Adding `tensorboard_logging_interval` argument to `TrainMonitor` could be the solution.

**Comment by KristianHolsheimer** [comment]
Thanks for you interest in coax!

And thanks for the suggestion. I agree, it work of be great to add this functionality.

I won't be able to make any changes myself until August. I'm traveling at moment, with no access to a computer and limited internet access.

If you would like to have a crack at it, I would really appreciate it.

In terms of implementation, I imagine we would need to add some accumulators similar to the `_ep_...` attrs, which would hold averages of per-episode metrics across multiple episodes (the number of episodes would be set by your new kwarg).

After that, it would be a matter of amending the `step` method to store and use those new accumulators.

Does that make sense?

**Comment by dandelin** [comment]
I've temporarily detoured the issue using another `SummaryWriter`, leaving `tensorboard_dir==None` in `TrainMonitor.__init__`.
Your idea sounds good to me; I will make a PR if I have some spare time.
