### ISSUE TITLE
Frozen Lake example has an invalid gym signature.

### ISSUE THREAD

**Issue by dbleyl** [coax-dev/coax#31]
**Describe the bug**

The example for Frozen Lake in the main branch of the docs isn't fully updated for the new version of gym's signature.

ValueError                                Traceback (most recent call last)
[<ipython-input-2-2f30ae32bda9>](https://localhost:8080/#) in <module>
     77 
     78     a = pi.mode(s)
---> 79     s, r, done, info = env.step(a)
     80 
     81     env.render()

ValueError: too many values to unpack (expected 4)

**Expected behavior**

Executing the notebook should not result in a ValueError.

**To Reproduce**

Colab notebook to repro the bug:

[- https://colab.research.google.com/...
](https://colab.research.google.com/github/coax-dev/coax/blob/main/doc/_notebooks/frozen_lake/double_qlearning.ipynb#scrollTo=LlGMYKEE09Et)

*Runtime used for this colab notebook: ... (e.g. CPU/GPU/TPU)*

Any.

**Additional context**

Simple fix, happy to contribute a pull request.

**Comment by dbleyl** [comment]
Pull request sent.

**Comment by KristianHolsheimer** [comment]
Thanks for reporting this!

This was fixed in #28, but we didn't bump the pypi version. I'll do that now.

**Comment by KristianHolsheimer** [comment]
Apologies, I didn't see that the evaluation episode loop hadn't been updated yet. Will check out #32 now.
