### ISSUE TITLE
Gymnasium Support

### ISSUE THREAD

**Issue by arjun-prakash** [coax-dev/coax#39]
**Is your feature request related to a problem? Please describe.**
Hi, I am trying to replicate the cart pole tutorial from: https://coax.readthedocs.io/en/latest/examples/cartpole/dqn.html

However, since gym is now deprecated I am using Gymnasium from Farama: https://github.com/Farama-Foundation/Gymnasium

The issue is that there is a check in _array.py that checks gym.Spaces which fails with gymnasium. This is specifically in the default_preprocessor. 

**Describe the solution you'd like**
Will Gymnasium be officially supported, or is there some work-around?

**Describe alternatives you've considered**
I am wondering if there is some wrapper I should be using?

**Additional context**
Cheers!

**Comment by younik** [comment]
A possible workaround is adding
```python
import sys
import gymnasium
sys.modules["gym"] = gymnasium
```

before coax import

**Comment by arjun-prakash** [comment]
Unfortunately I still run into a similar error: 
```  logger.warn(str(e))
Traceback (most recent call last):
  File "/home/apraka15/Documents/Projects/Reach-Avoid/gym-examples/gym_examples/scratch.py", line 37, in <module>
    q = coax.Q(func, env)
  File "/home/apraka15/Documents/Projects/Reach-Avoid/gym-examples/.env/lib/python3.10/site-packages/coax/_core/q.py", line 90, in __init__
    super().__init__(
  File "/home/apraka15/Documents/Projects/Reach-Avoid/gym-examples/.env/lib/python3.10/site-packages/coax/_core/base_func.py", line 60, in __init__
    raise TypeError(
TypeError: observation_space must be derived from gym.Space, got: <class 'gymnasium.spaces.box.Box'>```

**Comment by KristianHolsheimer** [comment]
Hi @arjun-prakash 

Thank you for your interest in coax and thanks for raising this.

There's a PR in flight that switches coax over to Gymnasium.
